
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.cookingwithmindthemoods.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.cookingwithmindthemoods.item.WholeGrainBreadItem;
import net.mcreator.cookingwithmindthemoods.item.VioletSuspiciousStewItem;
import net.mcreator.cookingwithmindthemoods.item.VeggieTacoItem;
import net.mcreator.cookingwithmindthemoods.item.VeggieSkewerItem;
import net.mcreator.cookingwithmindthemoods.item.VeggieSandwichItem;
import net.mcreator.cookingwithmindthemoods.item.TrippleVeggieSushiItem;
import net.mcreator.cookingwithmindthemoods.item.TripleSushiItem;
import net.mcreator.cookingwithmindthemoods.item.TripleFishSushiItem;
import net.mcreator.cookingwithmindthemoods.item.TastySandwichItem;
import net.mcreator.cookingwithmindthemoods.item.SyrupItem;
import net.mcreator.cookingwithmindthemoods.item.SweetbreadItem;
import net.mcreator.cookingwithmindthemoods.item.SweetberryjamItem;
import net.mcreator.cookingwithmindthemoods.item.SuspiciousSkewerItem;
import net.mcreator.cookingwithmindthemoods.item.SuperVeggieSandwichItem;
import net.mcreator.cookingwithmindthemoods.item.SuperMeatSandwichItem;
import net.mcreator.cookingwithmindthemoods.item.SuperFishSandwichItem;
import net.mcreator.cookingwithmindthemoods.item.SuperChocolateBreadItem;
import net.mcreator.cookingwithmindthemoods.item.StuffedMushroomsItem;
import net.mcreator.cookingwithmindthemoods.item.StrangeStewItem;
import net.mcreator.cookingwithmindthemoods.item.StrangeSkewerItem;
import net.mcreator.cookingwithmindthemoods.item.StickybreadItem;
import net.mcreator.cookingwithmindthemoods.item.StickyRiceItem;
import net.mcreator.cookingwithmindthemoods.item.SpicyhumusItem;
import net.mcreator.cookingwithmindthemoods.item.SparklySuspiciousStewItem;
import net.mcreator.cookingwithmindthemoods.item.SlightlyChocolateBreadItem;
import net.mcreator.cookingwithmindthemoods.item.SingleVeggieSushiItem;
import net.mcreator.cookingwithmindthemoods.item.SingleSushiItem;
import net.mcreator.cookingwithmindthemoods.item.SingleFishSushiItem;
import net.mcreator.cookingwithmindthemoods.item.SimmeredFruitItem;
import net.mcreator.cookingwithmindthemoods.item.SeafoodDinnerItem;
import net.mcreator.cookingwithmindthemoods.item.SavorysauceItem;
import net.mcreator.cookingwithmindthemoods.item.RottenTacoItem;
import net.mcreator.cookingwithmindthemoods.item.RottenSkewerItem;
import net.mcreator.cookingwithmindthemoods.item.RottenSandwichItem;
import net.mcreator.cookingwithmindthemoods.item.RiceItem;
import net.mcreator.cookingwithmindthemoods.item.PotatoSoupItem;
import net.mcreator.cookingwithmindthemoods.item.PorcelainPlateItem;
import net.mcreator.cookingwithmindthemoods.item.PaleSuspiciousStewItem;
import net.mcreator.cookingwithmindthemoods.item.NutBreadItem;
import net.mcreator.cookingwithmindthemoods.item.NutBarItem;
import net.mcreator.cookingwithmindthemoods.item.MoldyCheeseWheelItemItem;
import net.mcreator.cookingwithmindthemoods.item.MoldyCheeseItem;
import net.mcreator.cookingwithmindthemoods.item.MelonTartItem;
import net.mcreator.cookingwithmindthemoods.item.MeatTacoItem;
import net.mcreator.cookingwithmindthemoods.item.MeatSkewerItem;
import net.mcreator.cookingwithmindthemoods.item.MeatSandwichItem;
import net.mcreator.cookingwithmindthemoods.item.LoadedPotatoItem;
import net.mcreator.cookingwithmindthemoods.item.IndigoSuspiciousStewItem;
import net.mcreator.cookingwithmindthemoods.item.HardCandyItem;
import net.mcreator.cookingwithmindthemoods.item.GrilledCheeseItem;
import net.mcreator.cookingwithmindthemoods.item.FruitSkewerItem;
import net.mcreator.cookingwithmindthemoods.item.FriedTurtleEggItem;
import net.mcreator.cookingwithmindthemoods.item.FriedEggItem;
import net.mcreator.cookingwithmindthemoods.item.FragrantSuspiciousStewItem;
import net.mcreator.cookingwithmindthemoods.item.FishTacoItem;
import net.mcreator.cookingwithmindthemoods.item.FishSkewerItem;
import net.mcreator.cookingwithmindthemoods.item.FishSandwichItem;
import net.mcreator.cookingwithmindthemoods.item.FieryFiletItem;
import net.mcreator.cookingwithmindthemoods.item.FadedSuspiciousStewItem;
import net.mcreator.cookingwithmindthemoods.item.ExtremelystickybreadItem;
import net.mcreator.cookingwithmindthemoods.item.ExtremelyRottenSandwichItem;
import net.mcreator.cookingwithmindthemoods.item.ExtrasweetbreadItem;
import net.mcreator.cookingwithmindthemoods.item.DoubleVeggieSushiItem;
import net.mcreator.cookingwithmindthemoods.item.DoubleSushiItem;
import net.mcreator.cookingwithmindthemoods.item.DoubleFishSushiItem;
import net.mcreator.cookingwithmindthemoods.item.DillRelishItem;
import net.mcreator.cookingwithmindthemoods.item.CrispySuspiciousStewItem;
import net.mcreator.cookingwithmindthemoods.item.CornbreadItem;
import net.mcreator.cookingwithmindthemoods.item.CornTortillaItem;
import net.mcreator.cookingwithmindthemoods.item.CornItem;
import net.mcreator.cookingwithmindthemoods.item.CornCobItem;
import net.mcreator.cookingwithmindthemoods.item.ColorfulSuspiciousStewItem;
import net.mcreator.cookingwithmindthemoods.item.ChocolatesauceItem;
import net.mcreator.cookingwithmindthemoods.item.ChocolateItem;
import net.mcreator.cookingwithmindthemoods.item.ChickenDinnerItem;
import net.mcreator.cookingwithmindthemoods.item.CheeseWheelItemItem;
import net.mcreator.cookingwithmindthemoods.item.CheeseItem;
import net.mcreator.cookingwithmindthemoods.item.CheeseBucketItem;
import net.mcreator.cookingwithmindthemoods.item.CarrotBreadItem;
import net.mcreator.cookingwithmindthemoods.item.CarrotBreadDeluxeItem;
import net.mcreator.cookingwithmindthemoods.item.BeefStewItem;
import net.mcreator.cookingwithmindthemoods.item.AzureSuspiciousStewItem;
import net.mcreator.cookingwithmindthemoods.item.AppleCrispItem;
import net.mcreator.cookingwithmindthemoods.item.AncientStewItem;
import net.mcreator.cookingwithmindthemoods.item.AncientSkewerItem;
import net.mcreator.cookingwithmindthemoods.item.AncientJamItem;
import net.mcreator.cookingwithmindthemoods.item.AncientCheeseWheelItemItem;
import net.mcreator.cookingwithmindthemoods.item.AncientCheeseItem;
import net.mcreator.cookingwithmindthemoods.item.AgedCheeseWheelItemItem;
import net.mcreator.cookingwithmindthemoods.item.AgedCheeseItem;
import net.mcreator.cookingwithmindthemoods.CookingWithMindthemoodsMod;

public class CookingWithMindthemoodsModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(CookingWithMindthemoodsMod.MODID);
	public static final DeferredItem<Item> STICKYBREAD = REGISTRY.register("stickybread", StickybreadItem::new);
	public static final DeferredItem<Item> EXTREMELYSTICKYBREAD = REGISTRY.register("extremelystickybread", ExtremelystickybreadItem::new);
	public static final DeferredItem<Item> COOKINGTABLE = block(CookingWithMindthemoodsModBlocks.COOKINGTABLE);
	public static final DeferredItem<Item> SWEETBREAD = REGISTRY.register("sweetbread", SweetbreadItem::new);
	public static final DeferredItem<Item> EXTRASWEETBREAD = REGISTRY.register("extrasweetbread", ExtrasweetbreadItem::new);
	public static final DeferredItem<Item> SWEETBERRYJAM = REGISTRY.register("sweetberryjam", SweetberryjamItem::new);
	public static final DeferredItem<Item> SPICYHUMUS = REGISTRY.register("spicyhumus", SpicyhumusItem::new);
	public static final DeferredItem<Item> SAVORYSAUCE = REGISTRY.register("savorysauce", SavorysauceItem::new);
	public static final DeferredItem<Item> CHOCOLATESAUCE = REGISTRY.register("chocolatesauce", ChocolatesauceItem::new);
	public static final DeferredItem<Item> CHOCOLATE = REGISTRY.register("chocolate", ChocolateItem::new);
	public static final DeferredItem<Item> SLIGHTLY_CHOCOLATE_BREAD = REGISTRY.register("slightly_chocolate_bread", SlightlyChocolateBreadItem::new);
	public static final DeferredItem<Item> SUPER_CHOCOLATE_BREAD = REGISTRY.register("super_chocolate_bread", SuperChocolateBreadItem::new);
	public static final DeferredItem<Item> CARROT_BREAD = REGISTRY.register("carrot_bread", CarrotBreadItem::new);
	public static final DeferredItem<Item> CARROT_BREAD_DELUXE = REGISTRY.register("carrot_bread_deluxe", CarrotBreadDeluxeItem::new);
	public static final DeferredItem<Item> DILL_RELISH = REGISTRY.register("dill_relish", DillRelishItem::new);
	public static final DeferredItem<Item> CHEESE_WHEEL = block(CookingWithMindthemoodsModBlocks.CHEESE_WHEEL);
	public static final DeferredItem<Item> AGED_CHEESE_WHEEL = block(CookingWithMindthemoodsModBlocks.AGED_CHEESE_WHEEL);
	public static final DeferredItem<Item> ANCIENT_CHEESE_WHEEL = block(CookingWithMindthemoodsModBlocks.ANCIENT_CHEESE_WHEEL);
	public static final DeferredItem<Item> CHEESE = REGISTRY.register("cheese", CheeseItem::new);
	public static final DeferredItem<Item> AGED_CHEESE = REGISTRY.register("aged_cheese", AgedCheeseItem::new);
	public static final DeferredItem<Item> ANCIENT_CHEESE = REGISTRY.register("ancient_cheese", AncientCheeseItem::new);
	public static final DeferredItem<Item> CHEESE_WHEEL_ITEM = REGISTRY.register("cheese_wheel_item", CheeseWheelItemItem::new);
	public static final DeferredItem<Item> AGED_CHEESE_WHEEL_ITEM = REGISTRY.register("aged_cheese_wheel_item", AgedCheeseWheelItemItem::new);
	public static final DeferredItem<Item> ANCIENT_CHEESE_WHEEL_ITEM = REGISTRY.register("ancient_cheese_wheel_item", AncientCheeseWheelItemItem::new);
	public static final DeferredItem<Item> MOLDY_CHEESE_WHEEL = block(CookingWithMindthemoodsModBlocks.MOLDY_CHEESE_WHEEL);
	public static final DeferredItem<Item> MOLDY_CHEESE = REGISTRY.register("moldy_cheese", MoldyCheeseItem::new);
	public static final DeferredItem<Item> MOLDY_CHEESE_WHEEL_ITEM = REGISTRY.register("moldy_cheese_wheel_item", MoldyCheeseWheelItemItem::new);
	public static final DeferredItem<Item> WAXED_CHEESE_WHEEL = block(CookingWithMindthemoodsModBlocks.WAXED_CHEESE_WHEEL);
	public static final DeferredItem<Item> WAXED_AGED_CHEESE_WHEEL = block(CookingWithMindthemoodsModBlocks.WAXED_AGED_CHEESE_WHEEL);
	public static final DeferredItem<Item> WAXED_ANCIENT_CHEESE_WHEEL = block(CookingWithMindthemoodsModBlocks.WAXED_ANCIENT_CHEESE_WHEEL);
	public static final DeferredItem<Item> CHEESE_BUCKET = REGISTRY.register("cheese_bucket", CheeseBucketItem::new);
	public static final DeferredItem<Item> RICE = REGISTRY.register("rice", RiceItem::new);
	public static final DeferredItem<Item> RICE_SHOOTS = block(CookingWithMindthemoodsModBlocks.RICE_SHOOTS);
	public static final DeferredItem<Item> RICE_BOTTOM_STAGE_1 = block(CookingWithMindthemoodsModBlocks.RICE_BOTTOM_STAGE_1);
	public static final DeferredItem<Item> RICE_BOTTOM_STAGE_2 = block(CookingWithMindthemoodsModBlocks.RICE_BOTTOM_STAGE_2);
	public static final DeferredItem<Item> RICE_TOP_STAGE_1 = block(CookingWithMindthemoodsModBlocks.RICE_TOP_STAGE_1);
	public static final DeferredItem<Item> RICE_TOP_STAGE_2 = block(CookingWithMindthemoodsModBlocks.RICE_TOP_STAGE_2);
	public static final DeferredItem<Item> RICE_TOP_STAGE_3 = block(CookingWithMindthemoodsModBlocks.RICE_TOP_STAGE_3);
	public static final DeferredItem<Item> RICE_BOTTOM_STAGE_3 = block(CookingWithMindthemoodsModBlocks.RICE_BOTTOM_STAGE_3);
	public static final DeferredItem<Item> YOUNGISH_RICE_PLANT = block(CookingWithMindthemoodsModBlocks.YOUNGISH_RICE_PLANT);
	public static final DeferredItem<Item> SINGLE_PUMPKIN_PIE = block(CookingWithMindthemoodsModBlocks.SINGLE_PUMPKIN_PIE);
	public static final DeferredItem<Item> DOUBLE_PUMPKIN_PIE = block(CookingWithMindthemoodsModBlocks.DOUBLE_PUMPKIN_PIE);
	public static final DeferredItem<Item> TRIPLE_PUMPKIN_PIE = block(CookingWithMindthemoodsModBlocks.TRIPLE_PUMPKIN_PIE);
	public static final DeferredItem<Item> QUADRUPLE_PUMPKIN_PIE = block(CookingWithMindthemoodsModBlocks.QUADRUPLE_PUMPKIN_PIE);
	public static final DeferredItem<Item> MEGA_PUMPKIN_PIE = block(CookingWithMindthemoodsModBlocks.MEGA_PUMPKIN_PIE);
	public static final DeferredItem<Item> APPLE_CRISP = REGISTRY.register("apple_crisp", AppleCrispItem::new);
	public static final DeferredItem<Item> MELON_TART = REGISTRY.register("melon_tart", MelonTartItem::new);
	public static final DeferredItem<Item> SINGLE_MELON_TART = block(CookingWithMindthemoodsModBlocks.SINGLE_MELON_TART);
	public static final DeferredItem<Item> DOUBLE_MELON_TART = block(CookingWithMindthemoodsModBlocks.DOUBLE_MELON_TART);
	public static final DeferredItem<Item> TRIPLE_MELON_TART = block(CookingWithMindthemoodsModBlocks.TRIPLE_MELON_TART);
	public static final DeferredItem<Item> QUADRUPLE_TART = block(CookingWithMindthemoodsModBlocks.QUADRUPLE_TART);
	public static final DeferredItem<Item> MEGA_MELON_TART = block(CookingWithMindthemoodsModBlocks.MEGA_MELON_TART);
	public static final DeferredItem<Item> SINGLE_APPLE_CRISP = block(CookingWithMindthemoodsModBlocks.SINGLE_APPLE_CRISP);
	public static final DeferredItem<Item> DOUBLE_APPLE_CRISP = block(CookingWithMindthemoodsModBlocks.DOUBLE_APPLE_CRISP);
	public static final DeferredItem<Item> TRIPLE_APPLE_CRISP = block(CookingWithMindthemoodsModBlocks.TRIPLE_APPLE_CRISP);
	public static final DeferredItem<Item> QUADRUPLE_APPLE_CRISP = block(CookingWithMindthemoodsModBlocks.QUADRUPLE_APPLE_CRISP);
	public static final DeferredItem<Item> MEGA_APPLE_CRISP = block(CookingWithMindthemoodsModBlocks.MEGA_APPLE_CRISP);
	public static final DeferredItem<Item> STICKY_RICE = REGISTRY.register("sticky_rice", StickyRiceItem::new);
	public static final DeferredItem<Item> APPLE_BLOSSOMS_STAGE_1 = block(CookingWithMindthemoodsModBlocks.APPLE_BLOSSOMS_STAGE_1);
	public static final DeferredItem<Item> APPLE_BLOSSOMS_STAGE_2 = block(CookingWithMindthemoodsModBlocks.APPLE_BLOSSOMS_STAGE_2);
	public static final DeferredItem<Item> APPLE_BLOSSOMS_STAGE_3 = block(CookingWithMindthemoodsModBlocks.APPLE_BLOSSOMS_STAGE_3);
	public static final DeferredItem<Item> APPLE_BLOSSOMS_MATURE = block(CookingWithMindthemoodsModBlocks.APPLE_BLOSSOMS_MATURE);
	public static final DeferredItem<Item> VIOLET_SUSPICIOUS_STEW = REGISTRY.register("violet_suspicious_stew", VioletSuspiciousStewItem::new);
	public static final DeferredItem<Item> AZURE_SUSPICIOUS_STEW = REGISTRY.register("azure_suspicious_stew", AzureSuspiciousStewItem::new);
	public static final DeferredItem<Item> INDIGO_SUSPICIOUS_STEW = REGISTRY.register("indigo_suspicious_stew", IndigoSuspiciousStewItem::new);
	public static final DeferredItem<Item> CRISPY_SUSPICIOUS_STEW = REGISTRY.register("crispy_suspicious_stew", CrispySuspiciousStewItem::new);
	public static final DeferredItem<Item> COLORFUL_SUSPICIOUS_STEW = REGISTRY.register("colorful_suspicious_stew", ColorfulSuspiciousStewItem::new);
	public static final DeferredItem<Item> FADED_SUSPICIOUS_STEW = REGISTRY.register("faded_suspicious_stew", FadedSuspiciousStewItem::new);
	public static final DeferredItem<Item> PALE_SUSPICIOUS_STEW = REGISTRY.register("pale_suspicious_stew", PaleSuspiciousStewItem::new);
	public static final DeferredItem<Item> SPARKLY_SUSPICIOUS_STEW = REGISTRY.register("sparkly_suspicious_stew", SparklySuspiciousStewItem::new);
	public static final DeferredItem<Item> FRAGRANT_SUSPICIOUS_STEW = REGISTRY.register("fragrant_suspicious_stew", FragrantSuspiciousStewItem::new);
	public static final DeferredItem<Item> FRIED_EGG = REGISTRY.register("fried_egg", FriedEggItem::new);
	public static final DeferredItem<Item> FRIED_TURTLE_EGG = REGISTRY.register("fried_turtle_egg", FriedTurtleEggItem::new);
	public static final DeferredItem<Item> MEAT_SANDWICH = REGISTRY.register("meat_sandwich", MeatSandwichItem::new);
	public static final DeferredItem<Item> SUPER_MEAT_SANDWICH = REGISTRY.register("super_meat_sandwich", SuperMeatSandwichItem::new);
	public static final DeferredItem<Item> VEGGIE_SANDWICH = REGISTRY.register("veggie_sandwich", VeggieSandwichItem::new);
	public static final DeferredItem<Item> SUPER_VEGGIE_SANDWICH = REGISTRY.register("super_veggie_sandwich", SuperVeggieSandwichItem::new);
	public static final DeferredItem<Item> FISH_SANDWICH = REGISTRY.register("fish_sandwich", FishSandwichItem::new);
	public static final DeferredItem<Item> SUPER_FISH_SANDWICH = REGISTRY.register("super_fish_sandwich", SuperFishSandwichItem::new);
	public static final DeferredItem<Item> ROTTEN_SANDWICH = REGISTRY.register("rotten_sandwich", RottenSandwichItem::new);
	public static final DeferredItem<Item> EXTREMELY_ROTTEN_SANDWICH = REGISTRY.register("extremely_rotten_sandwich", ExtremelyRottenSandwichItem::new);
	public static final DeferredItem<Item> SIMMERED_FRUIT = REGISTRY.register("simmered_fruit", SimmeredFruitItem::new);
	public static final DeferredItem<Item> SYRUP = REGISTRY.register("syrup", SyrupItem::new);
	public static final DeferredItem<Item> WHOLE_GRAIN_BREAD = REGISTRY.register("whole_grain_bread", WholeGrainBreadItem::new);
	public static final DeferredItem<Item> GRILLED_CHEESE = REGISTRY.register("grilled_cheese", GrilledCheeseItem::new);
	public static final DeferredItem<Item> CHICKEN_DINNER = REGISTRY.register("chicken_dinner", ChickenDinnerItem::new);
	public static final DeferredItem<Item> SEAFOOD_DINNER = REGISTRY.register("seafood_dinner", SeafoodDinnerItem::new);
	public static final DeferredItem<Item> FIERY_FILET = REGISTRY.register("fiery_filet", FieryFiletItem::new);
	public static final DeferredItem<Item> STUFFED_MUSHROOMS = REGISTRY.register("stuffed_mushrooms", StuffedMushroomsItem::new);
	public static final DeferredItem<Item> LOADED_POTATO = REGISTRY.register("loaded_potato", LoadedPotatoItem::new);
	public static final DeferredItem<Item> FRUIT_SKEWER = REGISTRY.register("fruit_skewer", FruitSkewerItem::new);
	public static final DeferredItem<Item> VEGGIE_SKEWER = REGISTRY.register("veggie_skewer", VeggieSkewerItem::new);
	public static final DeferredItem<Item> FISH_SKEWER = REGISTRY.register("fish_skewer", FishSkewerItem::new);
	public static final DeferredItem<Item> MEAT_SKEWER = REGISTRY.register("meat_skewer", MeatSkewerItem::new);
	public static final DeferredItem<Item> SUSPICIOUS_SKEWER = REGISTRY.register("suspicious_skewer", SuspiciousSkewerItem::new);
	public static final DeferredItem<Item> BEEF_STEW = REGISTRY.register("beef_stew", BeefStewItem::new);
	public static final DeferredItem<Item> STRANGE_STEW = REGISTRY.register("strange_stew", StrangeStewItem::new);
	public static final DeferredItem<Item> STRANGE_SKEWER = REGISTRY.register("strange_skewer", StrangeSkewerItem::new);
	public static final DeferredItem<Item> ROTTEN_SKEWER = REGISTRY.register("rotten_skewer", RottenSkewerItem::new);
	public static final DeferredItem<Item> HARD_CANDY = REGISTRY.register("hard_candy", HardCandyItem::new);
	public static final DeferredItem<Item> TASTY_SANDWICH = REGISTRY.register("tasty_sandwich", TastySandwichItem::new);
	public static final DeferredItem<Item> POTATO_SOUP = REGISTRY.register("potato_soup", PotatoSoupItem::new);
	public static final DeferredItem<Item> SINGLE_SUSHI = REGISTRY.register("single_sushi", SingleSushiItem::new);
	public static final DeferredItem<Item> DOUBLE_SUSHI = REGISTRY.register("double_sushi", DoubleSushiItem::new);
	public static final DeferredItem<Item> TRIPLE_SUSHI = REGISTRY.register("triple_sushi", TripleSushiItem::new);
	public static final DeferredItem<Item> SINGLE_VEGGIE_SUSHI = REGISTRY.register("single_veggie_sushi", SingleVeggieSushiItem::new);
	public static final DeferredItem<Item> DOUBLE_VEGGIE_SUSHI = REGISTRY.register("double_veggie_sushi", DoubleVeggieSushiItem::new);
	public static final DeferredItem<Item> TRIPPLE_VEGGIE_SUSHI = REGISTRY.register("tripple_veggie_sushi", TrippleVeggieSushiItem::new);
	public static final DeferredItem<Item> SINGLE_FISH_SUSHI = REGISTRY.register("single_fish_sushi", SingleFishSushiItem::new);
	public static final DeferredItem<Item> DOUBLE_FISH_SUSHI = REGISTRY.register("double_fish_sushi", DoubleFishSushiItem::new);
	public static final DeferredItem<Item> TRIPLE_FISH_SUSHI = REGISTRY.register("triple_fish_sushi", TripleFishSushiItem::new);
	public static final DeferredItem<Item> NUT_BREAD = REGISTRY.register("nut_bread", NutBreadItem::new);
	public static final DeferredItem<Item> NUT_BAR = REGISTRY.register("nut_bar", NutBarItem::new);
	public static final DeferredItem<Item> PORCELAIN_PLATE = REGISTRY.register("porcelain_plate", PorcelainPlateItem::new);
	public static final DeferredItem<Item> EMPTY_PLATE = block(CookingWithMindthemoodsModBlocks.EMPTY_PLATE);
	public static final DeferredItem<Item> APPLE_PLATE = block(CookingWithMindthemoodsModBlocks.APPLE_PLATE);
	public static final DeferredItem<Item> BEETROOT_PLATE_1 = block(CookingWithMindthemoodsModBlocks.BEETROOT_PLATE_1);
	public static final DeferredItem<Item> BEETROOT_PLATE_2 = block(CookingWithMindthemoodsModBlocks.BEETROOT_PLATE_2);
	public static final DeferredItem<Item> BEETROOT_PLATE_3 = block(CookingWithMindthemoodsModBlocks.BEETROOT_PLATE_3);
	public static final DeferredItem<Item> BERRY_PLATE_1 = block(CookingWithMindthemoodsModBlocks.BERRY_PLATE_1);
	public static final DeferredItem<Item> BERRY_PLATE_2 = block(CookingWithMindthemoodsModBlocks.BERRY_PLATE_2);
	public static final DeferredItem<Item> BERRY_PLATE_3 = block(CookingWithMindthemoodsModBlocks.BERRY_PLATE_3);
	public static final DeferredItem<Item> GLOW_BERRY_PLATE_1 = block(CookingWithMindthemoodsModBlocks.GLOW_BERRY_PLATE_1);
	public static final DeferredItem<Item> GLOW_BERRY_PLATE_2 = block(CookingWithMindthemoodsModBlocks.GLOW_BERRY_PLATE_2);
	public static final DeferredItem<Item> GLOW_BERRY_PLATE_3 = block(CookingWithMindthemoodsModBlocks.GLOW_BERRY_PLATE_3);
	public static final DeferredItem<Item> GOLDEN_APPLE_PLATE = block(CookingWithMindthemoodsModBlocks.GOLDEN_APPLE_PLATE);
	public static final DeferredItem<Item> ENCHANTED_APPLE_PLATE = block(CookingWithMindthemoodsModBlocks.ENCHANTED_APPLE_PLATE);
	public static final DeferredItem<Item> BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.BREAD_PLATE);
	public static final DeferredItem<Item> SWEET_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.SWEET_BREAD_PLATE);
	public static final DeferredItem<Item> STICKY_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.STICKY_BREAD_PLATE);
	public static final DeferredItem<Item> CHOCOLATE_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.CHOCOLATE_BREAD_PLATE);
	public static final DeferredItem<Item> NUT_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.NUT_BREAD_PLATE);
	public static final DeferredItem<Item> CARROT_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.CARROT_BREAD_PLATE);
	public static final DeferredItem<Item> SUPER_SWEET_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.SUPER_SWEET_BREAD_PLATE);
	public static final DeferredItem<Item> SUPER_CARROT_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.SUPER_CARROT_BREAD_PLATE);
	public static final DeferredItem<Item> SUPER_CHOCOLATE_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.SUPER_CHOCOLATE_BREAD_PLATE);
	public static final DeferredItem<Item> SUPER_STICKY_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.SUPER_STICKY_BREAD_PLATE);
	public static final DeferredItem<Item> CARROT_PLATE_1 = block(CookingWithMindthemoodsModBlocks.CARROT_PLATE_1);
	public static final DeferredItem<Item> CARROT_PLATE_2 = block(CookingWithMindthemoodsModBlocks.CARROT_PLATE_2);
	public static final DeferredItem<Item> CARROT_PLATE_3 = block(CookingWithMindthemoodsModBlocks.CARROT_PLATE_3);
	public static final DeferredItem<Item> GOLDEN_CARROT_PLATE_1 = block(CookingWithMindthemoodsModBlocks.GOLDEN_CARROT_PLATE_1);
	public static final DeferredItem<Item> GOLDEN_CARROT_PLATE_2 = block(CookingWithMindthemoodsModBlocks.GOLDEN_CARROT_PLATE_2);
	public static final DeferredItem<Item> GOLDEN_CARROT_PLATE_3 = block(CookingWithMindthemoodsModBlocks.GOLDEN_CARROT_PLATE_3);
	public static final DeferredItem<Item> CHEESE_PLATE = block(CookingWithMindthemoodsModBlocks.CHEESE_PLATE);
	public static final DeferredItem<Item> AGED_CHEESE_PLATE = block(CookingWithMindthemoodsModBlocks.AGED_CHEESE_PLATE);
	public static final DeferredItem<Item> ANCIENT_CHEESE_PLATE = block(CookingWithMindthemoodsModBlocks.ANCIENT_CHEESE_PLATE);
	public static final DeferredItem<Item> MOLDY_CHEESE_PLATE = block(CookingWithMindthemoodsModBlocks.MOLDY_CHEESE_PLATE);
	public static final DeferredItem<Item> CHICKEN_DINNER_PLATE = block(CookingWithMindthemoodsModBlocks.CHICKEN_DINNER_PLATE);
	public static final DeferredItem<Item> NIBBLED_CHICKEN_DINNER_PLATE = block(CookingWithMindthemoodsModBlocks.NIBBLED_CHICKEN_DINNER_PLATE);
	public static final DeferredItem<Item> MUNCHED_CHICKEN_DINNER_PLATE = block(CookingWithMindthemoodsModBlocks.MUNCHED_CHICKEN_DINNER_PLATE);
	public static final DeferredItem<Item> CRUMBY_CHICKEN_DINNER_PLATE = block(CookingWithMindthemoodsModBlocks.CRUMBY_CHICKEN_DINNER_PLATE);
	public static final DeferredItem<Item> FIERY_FILET_PLATE = block(CookingWithMindthemoodsModBlocks.FIERY_FILET_PLATE);
	public static final DeferredItem<Item> NIBBLED_FIERY_FILET_PLATE = block(CookingWithMindthemoodsModBlocks.NIBBLED_FIERY_FILET_PLATE);
	public static final DeferredItem<Item> MUNCHED_FIERY_FILET_PLATE = block(CookingWithMindthemoodsModBlocks.MUNCHED_FIERY_FILET_PLATE);
	public static final DeferredItem<Item> CRUMBY_FIERY_FILET_PLATE = block(CookingWithMindthemoodsModBlocks.CRUMBY_FIERY_FILET_PLATE);
	public static final DeferredItem<Item> SEAFOOD_DINNER_PLATE = block(CookingWithMindthemoodsModBlocks.SEAFOOD_DINNER_PLATE);
	public static final DeferredItem<Item> NIBBLED_SEAFOOD_DINNER_PLATE = block(CookingWithMindthemoodsModBlocks.NIBBLED_SEAFOOD_DINNER_PLATE);
	public static final DeferredItem<Item> MUNCHED_SEAFOOD_DINNER_PLATE = block(CookingWithMindthemoodsModBlocks.MUNCHED_SEAFOOD_DINNER_PLATE);
	public static final DeferredItem<Item> CRUMBY_SEAFOOD_DINNER_PLATE = block(CookingWithMindthemoodsModBlocks.CRUMBY_SEAFOOD_DINNER_PLATE);
	public static final DeferredItem<Item> CHORUS_PLATE = block(CookingWithMindthemoodsModBlocks.CHORUS_PLATE);
	public static final DeferredItem<Item> CHOCOLATE_PLATE_1 = block(CookingWithMindthemoodsModBlocks.CHOCOLATE_PLATE_1);
	public static final DeferredItem<Item> CHOCOLATE_PLATE_2 = block(CookingWithMindthemoodsModBlocks.CHOCOLATE_PLATE_2);
	public static final DeferredItem<Item> CHOCOLATE_PLATE_3 = block(CookingWithMindthemoodsModBlocks.CHOCOLATE_PLATE_3);
	public static final DeferredItem<Item> RICE_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.RICE_BREAD_PLATE);
	public static final DeferredItem<Item> BOWL_PLATE = block(CookingWithMindthemoodsModBlocks.BOWL_PLATE);
	public static final DeferredItem<Item> COOKIE_PLATE_1 = block(CookingWithMindthemoodsModBlocks.COOKIE_PLATE_1);
	public static final DeferredItem<Item> COOKIE_PLATE_2 = block(CookingWithMindthemoodsModBlocks.COOKIE_PLATE_2);
	public static final DeferredItem<Item> COOKIE_PLATE_3 = block(CookingWithMindthemoodsModBlocks.COOKIE_PLATE_3);
	public static final DeferredItem<Item> COOKIE_PLATE_4 = block(CookingWithMindthemoodsModBlocks.COOKIE_PLATE_4);
	public static final DeferredItem<Item> COOKIE_PLATE_5 = block(CookingWithMindthemoodsModBlocks.COOKIE_PLATE_5);
	public static final DeferredItem<Item> COD_PLATE_1 = block(CookingWithMindthemoodsModBlocks.COD_PLATE_1);
	public static final DeferredItem<Item> COD_PLATE_2 = block(CookingWithMindthemoodsModBlocks.COD_PLATE_2);
	public static final DeferredItem<Item> COD_PLATE_3 = block(CookingWithMindthemoodsModBlocks.COD_PLATE_3);
	public static final DeferredItem<Item> COOKED_COD_PLATE_1 = block(CookingWithMindthemoodsModBlocks.COOKED_COD_PLATE_1);
	public static final DeferredItem<Item> COOKED_COD_PLATE_2 = block(CookingWithMindthemoodsModBlocks.COOKED_COD_PLATE_2);
	public static final DeferredItem<Item> COOKED_COD_PLATE_3 = block(CookingWithMindthemoodsModBlocks.COOKED_COD_PLATE_3);
	public static final DeferredItem<Item> SALMON_PLATE_1 = block(CookingWithMindthemoodsModBlocks.SALMON_PLATE_1);
	public static final DeferredItem<Item> SALMON_PLATE_2 = block(CookingWithMindthemoodsModBlocks.SALMON_PLATE_2);
	public static final DeferredItem<Item> SALMON_PLATE_3 = block(CookingWithMindthemoodsModBlocks.SALMON_PLATE_3);
	public static final DeferredItem<Item> COOKED_SALMON_PLATE_1 = block(CookingWithMindthemoodsModBlocks.COOKED_SALMON_PLATE_1);
	public static final DeferredItem<Item> COOKED_SALMON_PLATE_2 = block(CookingWithMindthemoodsModBlocks.COOKED_SALMON_PLATE_2);
	public static final DeferredItem<Item> COOKED_SALMON_PLATE_3 = block(CookingWithMindthemoodsModBlocks.COOKED_SALMON_PLATE_3);
	public static final DeferredItem<Item> ROTTEN_FLESH_PLATE = block(CookingWithMindthemoodsModBlocks.ROTTEN_FLESH_PLATE);
	public static final DeferredItem<Item> DRIED_KELP_PLATE = block(CookingWithMindthemoodsModBlocks.DRIED_KELP_PLATE);
	public static final DeferredItem<Item> FRIED_EGG_PLATE = block(CookingWithMindthemoodsModBlocks.FRIED_EGG_PLATE);
	public static final DeferredItem<Item> FRIED_TURTLE_EGG_PLATE = block(CookingWithMindthemoodsModBlocks.FRIED_TURTLE_EGG_PLATE);
	public static final DeferredItem<Item> RAW_BEEF_PLATE_1 = block(CookingWithMindthemoodsModBlocks.RAW_BEEF_PLATE_1);
	public static final DeferredItem<Item> RAW_BEEF_PLATE_2 = block(CookingWithMindthemoodsModBlocks.RAW_BEEF_PLATE_2);
	public static final DeferredItem<Item> RAW_BEEF_PLATE_3 = block(CookingWithMindthemoodsModBlocks.RAW_BEEF_PLATE_3);
	public static final DeferredItem<Item> RAW_PORK_PLATE_1 = block(CookingWithMindthemoodsModBlocks.RAW_PORK_PLATE_1);
	public static final DeferredItem<Item> RAW_PORK_PLATE_2 = block(CookingWithMindthemoodsModBlocks.RAW_PORK_PLATE_2);
	public static final DeferredItem<Item> RAW_PORK_PLATE_3 = block(CookingWithMindthemoodsModBlocks.RAW_PORK_PLATE_3);
	public static final DeferredItem<Item> BEEF_PLATE_1 = block(CookingWithMindthemoodsModBlocks.BEEF_PLATE_1);
	public static final DeferredItem<Item> BEEF_PLATE_2 = block(CookingWithMindthemoodsModBlocks.BEEF_PLATE_2);
	public static final DeferredItem<Item> BEEF_PLATE_3 = block(CookingWithMindthemoodsModBlocks.BEEF_PLATE_3);
	public static final DeferredItem<Item> PORK_PLATE_1 = block(CookingWithMindthemoodsModBlocks.PORK_PLATE_1);
	public static final DeferredItem<Item> PORK_PLATE_2 = block(CookingWithMindthemoodsModBlocks.PORK_PLATE_2);
	public static final DeferredItem<Item> PORK_PLATE_3 = block(CookingWithMindthemoodsModBlocks.PORK_PLATE_3);
	public static final DeferredItem<Item> RAW_HARE_PLATE = block(CookingWithMindthemoodsModBlocks.RAW_HARE_PLATE);
	public static final DeferredItem<Item> HARE_PLATE = block(CookingWithMindthemoodsModBlocks.HARE_PLATE);
	public static final DeferredItem<Item> RAW_FOWL_PLATE = block(CookingWithMindthemoodsModBlocks.RAW_FOWL_PLATE);
	public static final DeferredItem<Item> FOWL_PLATE = block(CookingWithMindthemoodsModBlocks.FOWL_PLATE);
	public static final DeferredItem<Item> RAW_MUTTON_PLATE_1 = block(CookingWithMindthemoodsModBlocks.RAW_MUTTON_PLATE_1);
	public static final DeferredItem<Item> RAW_MUTTON_PLATE_2 = block(CookingWithMindthemoodsModBlocks.RAW_MUTTON_PLATE_2);
	public static final DeferredItem<Item> RAW_MUTTON_PLATE_3 = block(CookingWithMindthemoodsModBlocks.RAW_MUTTON_PLATE_3);
	public static final DeferredItem<Item> MUTTON_PLATE_1 = block(CookingWithMindthemoodsModBlocks.MUTTON_PLATE_1);
	public static final DeferredItem<Item> MUTTON_PLATE_2 = block(CookingWithMindthemoodsModBlocks.MUTTON_PLATE_2);
	public static final DeferredItem<Item> MUTTON_PLATE_3 = block(CookingWithMindthemoodsModBlocks.MUTTON_PLATE_3);
	public static final DeferredItem<Item> POISON_POTATO_PLATE = block(CookingWithMindthemoodsModBlocks.POISON_POTATO_PLATE);
	public static final DeferredItem<Item> POTATO_PLATE_1 = block(CookingWithMindthemoodsModBlocks.POTATO_PLATE_1);
	public static final DeferredItem<Item> POTATO_PLATE_2 = block(CookingWithMindthemoodsModBlocks.POTATO_PLATE_2);
	public static final DeferredItem<Item> POTATO_PLATE_3 = block(CookingWithMindthemoodsModBlocks.POTATO_PLATE_3);
	public static final DeferredItem<Item> JACKET_PLATE_1 = block(CookingWithMindthemoodsModBlocks.JACKET_PLATE_1);
	public static final DeferredItem<Item> JACKET_PLATE_2 = block(CookingWithMindthemoodsModBlocks.JACKET_PLATE_2);
	public static final DeferredItem<Item> JACKET_PLATE_3 = block(CookingWithMindthemoodsModBlocks.JACKET_PLATE_3);
	public static final DeferredItem<Item> PUFFERFISH_PLATE = block(CookingWithMindthemoodsModBlocks.PUFFERFISH_PLATE);
	public static final DeferredItem<Item> CANDY_PLATE_1 = block(CookingWithMindthemoodsModBlocks.CANDY_PLATE_1);
	public static final DeferredItem<Item> CANDY_PLATE_2 = block(CookingWithMindthemoodsModBlocks.CANDY_PLATE_2);
	public static final DeferredItem<Item> CANDY_PLATE_3 = block(CookingWithMindthemoodsModBlocks.CANDY_PLATE_3);
	public static final DeferredItem<Item> STICKY_RICE_PLATE_1 = block(CookingWithMindthemoodsModBlocks.STICKY_RICE_PLATE_1);
	public static final DeferredItem<Item> STICKY_RICE_PLATE_2 = block(CookingWithMindthemoodsModBlocks.STICKY_RICE_PLATE_2);
	public static final DeferredItem<Item> STICKY_RICE_PLATE_3 = block(CookingWithMindthemoodsModBlocks.STICKY_RICE_PLATE_3);
	public static final DeferredItem<Item> STICKY_RICE_PLATE_4 = block(CookingWithMindthemoodsModBlocks.STICKY_RICE_PLATE_4);
	public static final DeferredItem<Item> STICKY_RICE_PLATE_5 = block(CookingWithMindthemoodsModBlocks.STICKY_RICE_PLATE_5);
	public static final DeferredItem<Item> NUT_BAR_PLATE_1 = block(CookingWithMindthemoodsModBlocks.NUT_BAR_PLATE_1);
	public static final DeferredItem<Item> NUT_BAR_PLATE_2 = block(CookingWithMindthemoodsModBlocks.NUT_BAR_PLATE_2);
	public static final DeferredItem<Item> NUT_BAR_PLATE_3 = block(CookingWithMindthemoodsModBlocks.NUT_BAR_PLATE_3);
	public static final DeferredItem<Item> NUT_BAR_PLATE_4 = block(CookingWithMindthemoodsModBlocks.NUT_BAR_PLATE_4);
	public static final DeferredItem<Item> NUT_BAR_PLATE_5 = block(CookingWithMindthemoodsModBlocks.NUT_BAR_PLATE_5);
	public static final DeferredItem<Item> MELON_PLATE_1 = block(CookingWithMindthemoodsModBlocks.MELON_PLATE_1);
	public static final DeferredItem<Item> MELON_PLATE_2 = block(CookingWithMindthemoodsModBlocks.MELON_PLATE_2);
	public static final DeferredItem<Item> MELON_PLATE_3 = block(CookingWithMindthemoodsModBlocks.MELON_PLATE_3);
	public static final DeferredItem<Item> SHINY_MELON_PLATE_1 = block(CookingWithMindthemoodsModBlocks.SHINY_MELON_PLATE_1);
	public static final DeferredItem<Item> SHINY_MELON_PLATE_2 = block(CookingWithMindthemoodsModBlocks.SHINY_MELON_PLATE_2);
	public static final DeferredItem<Item> SHINY_MELON_PLATE_3 = block(CookingWithMindthemoodsModBlocks.SHINY_MELON_PLATE_3);
	public static final DeferredItem<Item> SUSHI_PLATE_1 = block(CookingWithMindthemoodsModBlocks.SUSHI_PLATE_1);
	public static final DeferredItem<Item> SUSHI_PLATE_2 = block(CookingWithMindthemoodsModBlocks.SUSHI_PLATE_2);
	public static final DeferredItem<Item> SUSHI_PLATE_3 = block(CookingWithMindthemoodsModBlocks.SUSHI_PLATE_3);
	public static final DeferredItem<Item> VEGGIE_SUSHI_PLATE_1 = block(CookingWithMindthemoodsModBlocks.VEGGIE_SUSHI_PLATE_1);
	public static final DeferredItem<Item> VEGGIE_SUSHI_PLATE_2 = block(CookingWithMindthemoodsModBlocks.VEGGIE_SUSHI_PLATE_2);
	public static final DeferredItem<Item> VEGGIE_SUSHI_PLATE_3 = block(CookingWithMindthemoodsModBlocks.VEGGIE_SUSHI_PLATE_3);
	public static final DeferredItem<Item> FISH_SUSHI_PLATE_1 = block(CookingWithMindthemoodsModBlocks.FISH_SUSHI_PLATE_1);
	public static final DeferredItem<Item> FISH_SUSHI_PLATE_2 = block(CookingWithMindthemoodsModBlocks.FISH_SUSHI_PLATE_2);
	public static final DeferredItem<Item> FISH_SUSHI_PLATE_3 = block(CookingWithMindthemoodsModBlocks.FISH_SUSHI_PLATE_3);
	public static final DeferredItem<Item> SUPER_ROTTEN_SANDWICH_PLATE = block(CookingWithMindthemoodsModBlocks.SUPER_ROTTEN_SANDWICH_PLATE);
	public static final DeferredItem<Item> SUPER_FISHY_SANDWICH_PLATE = block(CookingWithMindthemoodsModBlocks.SUPER_FISHY_SANDWICH_PLATE);
	public static final DeferredItem<Item> SUPER_MEATY_SANDWICH_PLATE = block(CookingWithMindthemoodsModBlocks.SUPER_MEATY_SANDWICH_PLATE);
	public static final DeferredItem<Item> SUPER_VEGGIE_SANDWICH_PLATE = block(CookingWithMindthemoodsModBlocks.SUPER_VEGGIE_SANDWICH_PLATE);
	public static final DeferredItem<Item> TASTY_SANDWICH_PLATE = block(CookingWithMindthemoodsModBlocks.TASTY_SANDWICH_PLATE);
	public static final DeferredItem<Item> LOADED_POTATO_PLATE = block(CookingWithMindthemoodsModBlocks.LOADED_POTATO_PLATE);
	public static final DeferredItem<Item> CHEESE_SANDWICH_PLATE_1 = block(CookingWithMindthemoodsModBlocks.CHEESE_SANDWICH_PLATE_1);
	public static final DeferredItem<Item> CHEESE_SANDWICH_PLATE_2 = block(CookingWithMindthemoodsModBlocks.CHEESE_SANDWICH_PLATE_2);
	public static final DeferredItem<Item> CHEESE_SANDWICH_PLATE_3 = block(CookingWithMindthemoodsModBlocks.CHEESE_SANDWICH_PLATE_3);
	public static final DeferredItem<Item> FISH_SANDWICH_PLATE_1 = block(CookingWithMindthemoodsModBlocks.FISH_SANDWICH_PLATE_1);
	public static final DeferredItem<Item> FISH_SANDWICH_PLATE_2 = block(CookingWithMindthemoodsModBlocks.FISH_SANDWICH_PLATE_2);
	public static final DeferredItem<Item> FISH_SANDWICH_PLATE_3 = block(CookingWithMindthemoodsModBlocks.FISH_SANDWICH_PLATE_3);
	public static final DeferredItem<Item> MEAT_SANDWICH_PLATE_1 = block(CookingWithMindthemoodsModBlocks.MEAT_SANDWICH_PLATE_1);
	public static final DeferredItem<Item> MEAT_SANDWICH_PLATE_2 = block(CookingWithMindthemoodsModBlocks.MEAT_SANDWICH_PLATE_2);
	public static final DeferredItem<Item> MEAT_SANDWICH_PLATE_3 = block(CookingWithMindthemoodsModBlocks.MEAT_SANDWICH_PLATE_3);
	public static final DeferredItem<Item> ROTTEN_SANDWICH_PLATE_1 = block(CookingWithMindthemoodsModBlocks.ROTTEN_SANDWICH_PLATE_1);
	public static final DeferredItem<Item> ROTTEN_SANDWICH_PLATE_2 = block(CookingWithMindthemoodsModBlocks.ROTTEN_SANDWICH_PLATE_2);
	public static final DeferredItem<Item> ROTTEN_SANDWICH_PLATE_3 = block(CookingWithMindthemoodsModBlocks.ROTTEN_SANDWICH_PLATE_3);
	public static final DeferredItem<Item> VEGGIE_SANDWICH_PLATE_1 = block(CookingWithMindthemoodsModBlocks.VEGGIE_SANDWICH_PLATE_1);
	public static final DeferredItem<Item> VEGGIE_SANDWICH_PLATE_2 = block(CookingWithMindthemoodsModBlocks.VEGGIE_SANDWICH_PLATE_2);
	public static final DeferredItem<Item> VEGGIE_SANDWICH_PLATE_3 = block(CookingWithMindthemoodsModBlocks.VEGGIE_SANDWICH_PLATE_3);
	public static final DeferredItem<Item> FISH_KEBAB_PLATE_1 = block(CookingWithMindthemoodsModBlocks.FISH_KEBAB_PLATE_1);
	public static final DeferredItem<Item> FISH_KEBAB_PLATE_2 = block(CookingWithMindthemoodsModBlocks.FISH_KEBAB_PLATE_2);
	public static final DeferredItem<Item> FISH_KEBAB_PLATE_3 = block(CookingWithMindthemoodsModBlocks.FISH_KEBAB_PLATE_3);
	public static final DeferredItem<Item> FRUIT_KEBAB_PLATE_1 = block(CookingWithMindthemoodsModBlocks.FRUIT_KEBAB_PLATE_1);
	public static final DeferredItem<Item> FRUIT_KEBAB_PLATE_2 = block(CookingWithMindthemoodsModBlocks.FRUIT_KEBAB_PLATE_2);
	public static final DeferredItem<Item> FRUIT_KEBAB_PLATE_3 = block(CookingWithMindthemoodsModBlocks.FRUIT_KEBAB_PLATE_3);
	public static final DeferredItem<Item> MEAT_KEBAB_PLATE_1 = block(CookingWithMindthemoodsModBlocks.MEAT_KEBAB_PLATE_1);
	public static final DeferredItem<Item> MEAT_KEBAB_PLATE_2 = block(CookingWithMindthemoodsModBlocks.MEAT_KEBAB_PLATE_2);
	public static final DeferredItem<Item> MEAT_KEBAB_PLATE_3 = block(CookingWithMindthemoodsModBlocks.MEAT_KEBAB_PLATE_3);
	public static final DeferredItem<Item> ROTTEN_KEBAB_PLATE_1 = block(CookingWithMindthemoodsModBlocks.ROTTEN_KEBAB_PLATE_1);
	public static final DeferredItem<Item> ROTTEN_KEBAB_PLATE_2 = block(CookingWithMindthemoodsModBlocks.ROTTEN_KEBAB_PLATE_2);
	public static final DeferredItem<Item> ROTTEN_KEBAB_PLATE_3 = block(CookingWithMindthemoodsModBlocks.ROTTEN_KEBAB_PLATE_3);
	public static final DeferredItem<Item> STRANGE_KEBAB_PLATE_1 = block(CookingWithMindthemoodsModBlocks.STRANGE_KEBAB_PLATE_1);
	public static final DeferredItem<Item> STRANGE_KEBAB_PLATE_2 = block(CookingWithMindthemoodsModBlocks.STRANGE_KEBAB_PLATE_2);
	public static final DeferredItem<Item> STRANGE_KEBAB_PLATE_3 = block(CookingWithMindthemoodsModBlocks.STRANGE_KEBAB_PLATE_3);
	public static final DeferredItem<Item> SUS_KEBAB_PLATE_1 = block(CookingWithMindthemoodsModBlocks.SUS_KEBAB_PLATE_1);
	public static final DeferredItem<Item> SUS_KEBAB_PLATE_2 = block(CookingWithMindthemoodsModBlocks.SUS_KEBAB_PLATE_2);
	public static final DeferredItem<Item> SUS_KEBAB_PLATE_3 = block(CookingWithMindthemoodsModBlocks.SUS_KEBAB_PLATE_3);
	public static final DeferredItem<Item> VEGGIE_KEBAB_PLATE_1 = block(CookingWithMindthemoodsModBlocks.VEGGIE_KEBAB_PLATE_1);
	public static final DeferredItem<Item> VEGGIE_KEBAB_PLATE_2 = block(CookingWithMindthemoodsModBlocks.VEGGIE_KEBAB_PLATE_2);
	public static final DeferredItem<Item> VEGGIE_KEBAB_PLATE_3 = block(CookingWithMindthemoodsModBlocks.VEGGIE_KEBAB_PLATE_3);
	public static final DeferredItem<Item> MUSHROOM_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.MUSHROOM_STEW_PLATE);
	public static final DeferredItem<Item> BEETROOT_SOUP_PLATE = block(CookingWithMindthemoodsModBlocks.BEETROOT_SOUP_PLATE);
	public static final DeferredItem<Item> RABBIT_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.RABBIT_STEW_PLATE);
	public static final DeferredItem<Item> POTATO_SOUP_PLATE = block(CookingWithMindthemoodsModBlocks.POTATO_SOUP_PLATE);
	public static final DeferredItem<Item> BEEF_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.BEEF_STEW_PLATE);
	public static final DeferredItem<Item> STRANGE_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.STRANGE_STEW_PLATE);
	public static final DeferredItem<Item> SYRUP_PLATE = block(CookingWithMindthemoodsModBlocks.SYRUP_PLATE);
	public static final DeferredItem<Item> SIMMERED_FRUIT_PLATE = block(CookingWithMindthemoodsModBlocks.SIMMERED_FRUIT_PLATE);
	public static final DeferredItem<Item> AZURE_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.AZURE_STEW_PLATE);
	public static final DeferredItem<Item> COLORFUL_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.COLORFUL_STEW_PLATE);
	public static final DeferredItem<Item> CRISPY_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.CRISPY_STEW_PLATE);
	public static final DeferredItem<Item> FADED_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.FADED_STEW_PLATE);
	public static final DeferredItem<Item> FRAGRANT_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.FRAGRANT_STEW_PLATE);
	public static final DeferredItem<Item> INDIGO_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.INDIGO_STEW_PLATE);
	public static final DeferredItem<Item> PALE_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.PALE_STEW_PLATE);
	public static final DeferredItem<Item> SPARKLEY_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.SPARKLEY_STEW_PLATE);
	public static final DeferredItem<Item> VIOLET_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.VIOLET_STEW_PLATE);
	public static final DeferredItem<Item> STUFFED_MUSHROOM_PLATE = block(CookingWithMindthemoodsModBlocks.STUFFED_MUSHROOM_PLATE);
	public static final DeferredItem<Item> CORN_STAGE_1 = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_1);
	public static final DeferredItem<Item> CORN_STAGE_2 = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_2);
	public static final DeferredItem<Item> CORN_STAGE_3 = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_3);
	public static final DeferredItem<Item> CORN_STAGE_4_LOWER = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_4_LOWER);
	public static final DeferredItem<Item> CORN_STAGE_4_TOP = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_4_TOP);
	public static final DeferredItem<Item> CORN_STAGE_5_LOWER = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_5_LOWER);
	public static final DeferredItem<Item> CORN_STAGE_5_TOP = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_5_TOP);
	public static final DeferredItem<Item> CORN_STAGE_6_LOWER = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_6_LOWER);
	public static final DeferredItem<Item> CORN_STAGE_6_TOP = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_6_TOP);
	public static final DeferredItem<Item> CORN_STAGE_7_LOWER = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_7_LOWER);
	public static final DeferredItem<Item> CORN_STAGE_7_TOP = block(CookingWithMindthemoodsModBlocks.CORN_STAGE_7_TOP);
	public static final DeferredItem<Item> CORN = REGISTRY.register("corn", CornItem::new);
	public static final DeferredItem<Item> CORN_COB = REGISTRY.register("corn_cob", CornCobItem::new);
	public static final DeferredItem<Item> CORN_TORTILLA = REGISTRY.register("corn_tortilla", CornTortillaItem::new);
	public static final DeferredItem<Item> CORNBREAD = REGISTRY.register("cornbread", CornbreadItem::new);
	public static final DeferredItem<Item> FISH_TACO = REGISTRY.register("fish_taco", FishTacoItem::new);
	public static final DeferredItem<Item> VEGGIE_TACO = REGISTRY.register("veggie_taco", VeggieTacoItem::new);
	public static final DeferredItem<Item> MEAT_TACO = REGISTRY.register("meat_taco", MeatTacoItem::new);
	public static final DeferredItem<Item> ROTTEN_TACO = REGISTRY.register("rotten_taco", RottenTacoItem::new);
	public static final DeferredItem<Item> TORTILLA_PLATE_1 = block(CookingWithMindthemoodsModBlocks.TORTILLA_PLATE_1);
	public static final DeferredItem<Item> TORTILLA_PLATE_2 = block(CookingWithMindthemoodsModBlocks.TORTILLA_PLATE_2);
	public static final DeferredItem<Item> TORTILLA_PLATE_3 = block(CookingWithMindthemoodsModBlocks.TORTILLA_PLATE_3);
	public static final DeferredItem<Item> CORN_PLATE_1 = block(CookingWithMindthemoodsModBlocks.CORN_PLATE_1);
	public static final DeferredItem<Item> CORN_PLATE_2 = block(CookingWithMindthemoodsModBlocks.CORN_PLATE_2);
	public static final DeferredItem<Item> CORN_PLATE_3 = block(CookingWithMindthemoodsModBlocks.CORN_PLATE_3);
	public static final DeferredItem<Item> CORN_COB_PLATE_1 = block(CookingWithMindthemoodsModBlocks.CORN_COB_PLATE_1);
	public static final DeferredItem<Item> CORN_COB_PLATE_2 = block(CookingWithMindthemoodsModBlocks.CORN_COB_PLATE_2);
	public static final DeferredItem<Item> CORN_COB_PLATE_3 = block(CookingWithMindthemoodsModBlocks.CORN_COB_PLATE_3);
	public static final DeferredItem<Item> CORN_BREAD_PLATE = block(CookingWithMindthemoodsModBlocks.CORN_BREAD_PLATE);
	public static final DeferredItem<Item> FISH_TACO_PLATE = block(CookingWithMindthemoodsModBlocks.FISH_TACO_PLATE);
	public static final DeferredItem<Item> VEGGIE_TACO_PLATE = block(CookingWithMindthemoodsModBlocks.VEGGIE_TACO_PLATE);
	public static final DeferredItem<Item> MEAT_TACO_PLATE = block(CookingWithMindthemoodsModBlocks.MEAT_TACO_PLATE);
	public static final DeferredItem<Item> ROTTEN_TACO_PLATE = block(CookingWithMindthemoodsModBlocks.ROTTEN_TACO_PLATE);
	public static final DeferredItem<Item> BRISTLESPROUT_1 = block(CookingWithMindthemoodsModBlocks.BRISTLESPROUT_1);
	public static final DeferredItem<Item> BRISTLESPROUT_2 = block(CookingWithMindthemoodsModBlocks.BRISTLESPROUT_2);
	public static final DeferredItem<Item> BRISTLESPROUT_3 = block(CookingWithMindthemoodsModBlocks.BRISTLESPROUT_3);
	public static final DeferredItem<Item> BRISTLESPROUT_4 = doubleBlock(CookingWithMindthemoodsModBlocks.BRISTLESPROUT_4);
	public static final DeferredItem<Item> BRISTLESPROUT_5 = doubleBlock(CookingWithMindthemoodsModBlocks.BRISTLESPROUT_5);
	public static final DeferredItem<Item> BRISTLESPROUT_6 = doubleBlock(CookingWithMindthemoodsModBlocks.BRISTLESPROUT_6);
	public static final DeferredItem<Item> TORCHFLOWER_OPEN_1 = block(CookingWithMindthemoodsModBlocks.TORCHFLOWER_OPEN_1);
	public static final DeferredItem<Item> TORCHFLOWER_OPEN_2 = block(CookingWithMindthemoodsModBlocks.TORCHFLOWER_OPEN_2);
	public static final DeferredItem<Item> TORCHFLOWER_OPEN_3 = block(CookingWithMindthemoodsModBlocks.TORCHFLOWER_OPEN_3);
	public static final DeferredItem<Item> TORCHFLOWER_SPENT = block(CookingWithMindthemoodsModBlocks.TORCHFLOWER_SPENT);
	public static final DeferredItem<Item> PITCHERPLANT_OPEN_1 = doubleBlock(CookingWithMindthemoodsModBlocks.PITCHERPLANT_OPEN_1);
	public static final DeferredItem<Item> PITCHERPLANT_OPEN_2 = doubleBlock(CookingWithMindthemoodsModBlocks.PITCHERPLANT_OPEN_2);
	public static final DeferredItem<Item> PITCHERPLANT_SPENT = doubleBlock(CookingWithMindthemoodsModBlocks.PITCHERPLANT_SPENT);
	public static final DeferredItem<Item> BRISTLESPROUT_OPEN_1 = doubleBlock(CookingWithMindthemoodsModBlocks.BRISTLESPROUT_OPEN_1);
	public static final DeferredItem<Item> BRISTLESPROUT_OPEN_2 = doubleBlock(CookingWithMindthemoodsModBlocks.BRISTLESPROUT_OPEN_2);
	public static final DeferredItem<Item> BRISTLESPROUT_SPENT_1 = doubleBlock(CookingWithMindthemoodsModBlocks.BRISTLESPROUT_SPENT_1);
	public static final DeferredItem<Item> BRISTLESPROUT_SPENT_2 = doubleBlock(CookingWithMindthemoodsModBlocks.BRISTLESPROUT_SPENT_2);
	public static final DeferredItem<Item> STAR_PETALS_1_PURPLE = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_1_PURPLE);
	public static final DeferredItem<Item> STAR_PETALS_2_PURPLE = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_2_PURPLE);
	public static final DeferredItem<Item> STAR_PETALS_3_PURPLE = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_3_PURPLE);
	public static final DeferredItem<Item> STAR_PETALS_4_PURPLE = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_4_PURPLE);
	public static final DeferredItem<Item> STAR_PETALS_4_GOLD = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_4_GOLD);
	public static final DeferredItem<Item> STAR_PETALS_3_GOLD = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_3_GOLD);
	public static final DeferredItem<Item> STAR_PETALS_2_GOLD = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_2_GOLD);
	public static final DeferredItem<Item> STAR_PETALS_1_GOLD = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_1_GOLD);
	public static final DeferredItem<Item> STAR_PETALS_4_ORANGE = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_4_ORANGE);
	public static final DeferredItem<Item> STAR_PETALS_3_ORANGE = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_3_ORANGE);
	public static final DeferredItem<Item> STAR_PETALS_2_ORANGE = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_2_ORANGE);
	public static final DeferredItem<Item> STAR_PETALS_1_ORANGE = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_1_ORANGE);
	public static final DeferredItem<Item> STAR_PETALS_4_PINK = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_4_PINK);
	public static final DeferredItem<Item> STAR_PETALS_3_PINK = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_3_PINK);
	public static final DeferredItem<Item> STAR_PETALS_2_PINK = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_2_PINK);
	public static final DeferredItem<Item> STAR_PETALS_1_PINK = block(CookingWithMindthemoodsModBlocks.STAR_PETALS_1_PINK);
	public static final DeferredItem<Item> STAR_CROP_1 = block(CookingWithMindthemoodsModBlocks.STAR_CROP_1);
	public static final DeferredItem<Item> STAR_CROP_2 = block(CookingWithMindthemoodsModBlocks.STAR_CROP_2);
	public static final DeferredItem<Item> STAR_CROP_3 = block(CookingWithMindthemoodsModBlocks.STAR_CROP_3);
	public static final DeferredItem<Item> ANCIENT_JAM = REGISTRY.register("ancient_jam", AncientJamItem::new);
	public static final DeferredItem<Item> ANCIENT_SKEWER = REGISTRY.register("ancient_skewer", AncientSkewerItem::new);
	public static final DeferredItem<Item> ANCIENT_STEW = REGISTRY.register("ancient_stew", AncientStewItem::new);
	public static final DeferredItem<Item> ANCIENT_KEBAB_PLATE_1 = block(CookingWithMindthemoodsModBlocks.ANCIENT_KEBAB_PLATE_1);
	public static final DeferredItem<Item> ANCIENT_KEBAB_PLATE_2 = block(CookingWithMindthemoodsModBlocks.ANCIENT_KEBAB_PLATE_2);
	public static final DeferredItem<Item> ANCIENT_KEBAB_PLATE_3 = block(CookingWithMindthemoodsModBlocks.ANCIENT_KEBAB_PLATE_3);
	public static final DeferredItem<Item> ANCIENT_STEW_PLATE = block(CookingWithMindthemoodsModBlocks.ANCIENT_STEW_PLATE);

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
