modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="cooking_with_mindthemoods"
version="1.0.0"
displayName="Cooking with Mindthemoods"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mindthemoods"
description="Adds some foods and things."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.cooking_with_mindthemoods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration