modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="cooking_with_mindthemoods"
version="1.0.0"
displayName="Cooking with Mindthemoods"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mindthemoods"
description="Adds some foods and things."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.cooking_with_mindthemoods]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cooking_with_mindthemoods]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




[[mixins]]
    config="mixins.cooking_with_mindthemoods.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration